networks:
  participa:
    name: participa
volumes:
  postgres:
  mysql:
services:
  apache:
    image: php:8.2-apache-participa
    volumes:
      - ./:/var/www/html/
    networks:
      - participa
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_DB: '${DB_DATABASE:-laravel}'
      POSTGRES_USER: '${DB_USERNAME:-postgres}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    networks:
      - participa
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE}', '-U', '${DB_USERNAME}']
      retries: 3
      timeout: 5s
  mailpit:
    image: 'axllent/mailpit'
    networks:
      - participa
    ports:
      - "0.0.0.0:8025:8025"
  adminer:
    image: adminer
    networks:
      - participa
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
      - ADMINER_DEFAULT_DB_HOST=postgres
      - ADMINER_DEFAULT_DB_NAME='${DB_DATABASE:-laravel}'
