@extends('layouts.app')

@section('content')
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <h1 class="display-4 mb-4 fw-bold" style="color: #3d93a9; border-bottom: 3px solid #f2a440; padding-bottom: 10px;">
                Sobre o CBEE
            </h1>

            <div class="shadow-sm p-4 mb-5 bg-white rounded border-start border-4" style="border-color: #f2a440 !important;">
                <p style="text-align: justify; line-height: 1.6;">
                    O XV Congresso Brasileiro de Etnobiologia e Etnoecologia irá reunir pesquisadores das áreas de ciências naturais e humanas, representantes de ONGs e agências de governos, ativistas e representantes/lideranças dos povos indígenas e comunidades e povos tradicionais do Brasil todo para socializar os avanços científicos (tanto teóricos quanto metodológicos), éticos e jurídicos, ao longo das últimas três décadas, relacionados ao conhecimento ecológico tradicional, bem como debater sobre as grandes ameaças atuais à sociobiodiversidade do planeta. O tema escolhido para esta edição do CBEE "Saberes e Territórios Biodiversos: memória, luta e cuidado" - aponta para dimensões fundamentais para a pesquisa acadêmica em nossos tempos. Nos últimos anos, o ensino superior brasileiro passou por uma mudança profunda relacionada às políticas de ações afirmativas, tanto pela implementação de cotas étnico-raciais quanto pela criação de programas de inclusão e reconhecimento dos mestres e mestras dos saberes tradicionais nos processos de ensino e aprendizagem. Ao mesmo tempo, inicia-se uma série de debates para formulação de políticas públicas voltadas ao fomento de pesquisas interculturais, um campo ainda incipiente e com pouca atenção na agenda acadêmica. Por outro lado, o cenário de aceleração da crise ambiental torna ainda mais urgentes pesquisas interdisciplinares e interculturais que tratem das correlações entre a luta das comunidades em defesa de seus territórios e uma prática de cuidado e regeneração das bases da vida, tão ameaçadas pelo avanço de modelos de desenvolvimento predatórios.
                </p>
                <p style="text-align: justify; line-height: 1.6;">
                    Vale destacar que as últimas duas décadas têm sido marcadas, no campo acadêmico, por uma reaproximação e diálogos entre as ciências humanas e naturais, particularmente entre a antropologia e biologia. Não só as questões referentes às políticas de conservação têm sido objeto de crescente interesse da antropologia, como também a virada ontológica e os estudos multiespécies representam um alargamento do escopo do fazer antropológico, em uma clara ruptura dos dualismos que marcaram por tanto tempo a ciência moderna. No campo da biologia, por outro lado, desde a década de 1990, particularmente com a fundação da SBEE, se expande o número de profissionais e estudantes que também buscam superar os determinismos e essencialismos positivistas, produzindo pesquisas que levem em conta a complexas e diversas formas com que histórias humanas e mais que humanas se entrelaçam na constituição da sociobiodiversidade. São desses (re)encontros entre antropologia e biologia que tem surgido as mais fecundas narrativas capazes de orientar outros modos de produzir mundos, desde os estudos de ecologia histórica e etnobotânica que revelaram o caráter eminentemente humano das florestas tropicais, como das etnografias que evidenciam as diversas sociabilidades imbricadas em sistemas agrícolas tradicionais e outros modos de manejo e produção de paisagens biodiversas.
                </p>
                <p style="text-align: justify; line-height: 1.6;">
                    O XV Congresso Brasileiro de Etnobiologia e Etnoecologia proporcionará aos profissionais envolvidos uma experiência de alto valor acadêmico, científico e formativo, marcada pelo diálogo entre entre ciências naturais, humanas e saberes tradicionais, por meio de perspectivas interdisciplinares e interculturais. A organização do evento envolverá docentes, pesquisadores/as, técnicos/as e estudantes de diversas instituições, que terão a oportunidade de participar ativamente em processos de diálogo intercultural, construção coletiva de conhecimento e produção científica interdisciplinar. A realização do congresso também fortalecerá redes de pesquisa, ampliando a cooperação entre universidades, órgãos públicos, movimentos sociais e organizações da sociedade civil. Essa articulação permitirá a troca de metodologias participativas, experiências de pesquisa em contextos interculturais e práticas de salvaguarda de conhecimentos tradicionais, contribuindo para a consolidação de uma etnobiologia política e decolonial no Brasil. Para os/as profissionais das áreas de ensino e pesquisa, o evento constituirá um espaço privilegiado para atualização teórica, aprofundamento ético e metodológico, além de oportunidades de publicação e difusão dos resultados em diversos formatos. Para os(as) profissionais oriundos(as) de comunidades tradicionais e movimentos sociais, a participação no congresso possibilitará o fortalecimento de capacidades técnicas e políticas relacionadas à defesa dos territórios, à gestão dos bens comuns e à formulação de políticas públicas para a sociobiodiversidade. Assim, o CBEE consolidará um ambiente de aprendizado mútuo, fortalecimento de redes e reconhecimento dos diferentes modos de produzir e compartilhar conhecimento — aspectos fundamentais para o avanço científico e social da etnobiologia brasileira.
                </p>
            </div>
        </div>
    </div>
</div>
@endsection